export const AuthActionTypes = {
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',

    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    LOGOUT_USER: 'LOGOUT_USER', 
    CLEAR_AUTH_ERROR_STATE: 'CLEAR_AUTH_ERROR_STATE',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    RESET_PASSWORD_START: 'RESET_PASSWORD_START',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS', 
    RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',

    VERIFY_TOKEN: 'VERIFY_TOKEN',

    CHANGE_PASSWORD_START: 'CHANGE_PASSWORD_START',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',

}